import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Plus_Jakarta_Sans } from "next/font/google";

const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (

    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <Providers>
          <main>
            {children}
          </main>
        </Providers>
        </body>
    </html>
  );
}
